NAME(WEB49_OPCODE_V128_LOAD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD8X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD8X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD16X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD16X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD32X2_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD32X2_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD8_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD16_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD32_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD64_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_STORE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_CONST) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SHUFFLE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SWIZZLE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_SPLAT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_EXTRACT_LANE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_EXTRACT_LANE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTRACT_LANE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTRACT_LANE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTRACT_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTRACT_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_EXTRACT_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_EXTRACT_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_REPLACE_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_LT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_LT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_GT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_GT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_LE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_LE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_GE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_GE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_LT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_LT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_GT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_GT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_LE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_LE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_GE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_GE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_LT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_LT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_GT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_GT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_LE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_LE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_GE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_GE_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_LT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_GT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_LE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_GE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_LT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_GT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_LE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_GE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_NOT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_AND) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_ANDNOT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_OR) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_XOR) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_BITSELECT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_ANY_TRUE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD8_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD16_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD32_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD64_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_STORE8_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_STORE16_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_STORE32_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_STORE64_LANE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD32_ZERO) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_V128_LOAD64_ZERO) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_DEMOTE_F64X2_ZERO) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_PROMOTE_LOW_F32X4) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_POPCNT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_ALL_TRUE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_BITMASK) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_NARROW_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_NARROW_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_CEIL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_FLOOR) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_TRUNC) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_NEAREST) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SHL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SHR_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SHR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_ADD_SAT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_ADD_SAT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SUB_SAT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_SUB_SAT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_CEIL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_FLOOR) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_MIN_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_MIN_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_MAX_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_MAX_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_TRUNC) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I8X16_AVGR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTADD_PAIRWISE_I8X16_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTADD_PAIRWISE_I8X16_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTADD_PAIRWISE_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTADD_PAIRWISE_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_Q15MULR_SAT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_ALL_TRUE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_BITMASK) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_NARROW_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_NARROW_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTEND_LOW_I8X16_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTEND_HIGH_I8X16_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTEND_LOW_I8X16_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTEND_HIGH_I8X16_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SHL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SHR_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SHR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_ADD_SAT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_ADD_SAT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SUB_SAT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_SUB_SAT_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_NEAREST) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_MUL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_MIN_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_MIN_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_MAX_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_MAX_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_AVGR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTMUL_LOW_I8X16_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTMUL_HIGH_I8X16_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTMUL_LOW_I8X16_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I16X8_EXTMUL_HIGH_I8X16_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_ALL_TRUE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_BITMASK) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTEND_LOW_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTEND_HIGH_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTEND_LOW_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTEND_HIGH_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_SHL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_SHR_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_SHR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_MUL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_MIN_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_MIN_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_MAX_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_MAX_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_DOT_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTMUL_LOW_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTMUL_HIGH_I16X8_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTMUL_LOW_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_EXTMUL_HIGH_I16X8_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_ALL_TRUE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_BITMASK) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTEND_LOW_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTEND_HIGH_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTEND_LOW_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTEND_HIGH_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_SHL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_SHR_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_SHR_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_MUL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EQ) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_NE) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_LT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_GT_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_LE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_GE_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTMUL_LOW_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTMUL_HIGH_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTMUL_LOW_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I64X2_EXTMUL_HIGH_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_SQRT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_MUL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_DIV) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_MIN) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_MAX) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_PMIN) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_PMAX) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_ABS) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_NEG) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_SQRT) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_ADD) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_SUB) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_MUL) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_DIV) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_MIN) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_MAX) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_PMIN) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_PMAX) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_TRUNC_SAT_F32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_TRUNC_SAT_F32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_CONVERT_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F32X4_CONVERT_I32X4_U) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_TRUNC_SAT_F64X2_S_ZERO) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_I32X4_TRUNC_SAT_F64X2_U_ZERO) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_CONVERT_LOW_I32X4_S) {
    head += 0;
    NEXT();
}
NAME(WEB49_OPCODE_F64X2_CONVERT_LOW_I32X4_U) {
    head += 0;
    NEXT();
}