#!/usr/bin/env sh

set -e

DIR=$(mktemp -d)

where=BUILD
BUILD_ARGS=
RUN_ARGS=
for var in "$@"
do
    if [ "$var" = "--" ]
    then
        where=RUN
    else
        if [ "$where" = "BUILD" ]
        then
            BUILD_ARGS="$BUILD_ARGS $var"
        else
            RUN_ARGS="$RUN_ARGS $var"
        fi
    fi
done

$(dirname $0)/emraylib $BUILD_ARGS -o $DIR/game.wasm
$(dirname $0)/raywasm $DIR/game.wasm $RUN_ARGS
