
#if !defined(WEB49_HEADER_CONFIG)
#define WEB49_HEADER_CONFIG

#define WEB49_CHECK_BOUNDS 1

#define WEB49_DEBUG_DIE 1
#define WEB49_OPT_CONST 0

#define WEB49_COUNT_ALLOC 0
#define WEB49_PRINT_AST 0
#define WEB49_PRINT_INSTR 0
#define WEB49_PRINT_INSTR_DEPTH 0

#define WEB49_USE_SWITCH 1
// #define WEB49_USE_SWITCH 0

#endif
