name: Builds
on: [push]
jobs:
  linux-web49:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-O3 -fomit-frame-pointer' all
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-release
          path:  |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  linux-web49-warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-g3' CFLAGS='-Wall -Wextra -Werror -Wno-unused-parameter'
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-debug
          path:  |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  macos-web49:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-O3 -fomit-frame-pointer'
      - uses: actions/upload-artifact@v3
        with:
          name: web49-mac-release
          path: |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm