name: Builds Web49
on: [push]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.25
          actions-cache-folder: 'emsdk-cache'
      - run: make CC=gcc OPT='-O3 -fomit-frame-pointer -flto' all
      - run: sudo cp bin/miniwasm /usr/bin/miniwasm
      - run: pushd ./; git clone https://github.com/wasm3/wasm3 && cd wasm3 && cmake . && sudo make -Bj install; popd
      - run: sudo apt install -y python3 python3-pip
      - run: pip3 install matplotlib
      - run: python3 bench.py
      - uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path:  |
            test/bench/fannkuch-redux.png
            test/bench/mandelbrot.png
            test/bench/binary-trees.png
            test/bench/nop.png
            test/bench/fib.png
            test/bench/mandelbrot-simd.png
            test/bench/fasta.png
            test/bench/nbody.png
            test/bench/fibf.png
            test/bench/coremark.png
  web49-windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
      - run: make -j4 UNAME_S=Windows CC=gcc OPT='-O3 -fomit-frame-pointer' install INSTALL=web49-windows-release
      - uses: actions/upload-artifact@v3
        with:
          name: web49-windows-release
          path: web49-windows-release
  # web49-freebsd-release:
  #   runs-on: macos-12
  #   steps:
  #     - uses: actions/checkout@v3
  #     - id: freebsd
  #       uses: vmactions/freebsd-vm@v0
  #       with:
  #         usesh: true
  #         prepare: |
  #           pkg install -y gcc emscripten libX11 libXcursor libXi libXrandr libGL libXinerama
  #         run: |
  #           make -j4 CC=gcc OPT='-O3 -fomit-frame-pointer -flto' install INSTALL=web49-freebsd-release
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: web49-freebsd-release
  #         path: web49-freebsd-release
  web49-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev emscripten
      - run: make -j4 CC=gcc OPT='-O3 -fomit-frame-pointer -flto' install INSTALL=web49-linux-release
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-release
          path: web49-linux-release
  web49-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev emscripten
      - run: make -j4 CC=cc OPT='-g3' CFLAGS='-Wall -Wextra -Werror -Wno-unused-parameter' install INSTALL=web49-linux-debug
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-debug
          path: web49-linux-debug
  macos-web49:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: brew install emscripten
      - run: make -j4 CC=clang UNAME_S=Darwin OPT='-O3 -fomit-frame-pointer -flto' install INSTALL=web49-mac-release 
      - uses: actions/upload-artifact@v3
        with:
          name: web49-mac-release
          path: web49-mac-release