name: Builds
on: [push]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=gcc OPT='-O3 -fomit-frame-pointer -flto' all
      - run: sudo cp bin/miniwasm /usr/bin/miniwasm
      - run: pushd ./; git clone https://github.com/wasm3/wasm3 && cd wasm3 && cmake . && sudo make -Bj install; popd
      - run: curl https://get.wasmer.io -sSfL | sh
      - run: curl https://wasmtime.dev/install.sh -sSf | bash
      - run: sudo apt install -y python3 python3-pip
      - run: pip3 install matplotlib
      - run: python3 bench.py
      - uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path:  |
            test/bench/fannkuch-redux.png
            test/bench/mandelbrot.png
            test/bench/binary-trees.png
            test/bench/nop.png
            test/bench/fib.png
            test/bench/mandelbrot-simd.png
            test/bench/fasta.png
            test/bench/nbody.png
  linux-web49:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-O3 -fomit-frame-pointer' all
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-release
          path:  |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  linux-web49-warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-g3' CFLAGS='-Wall -Wextra -Werror -Wno-unused-parameter'
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-debug
          path:  |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  macos-web49:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make CC=cc OPT='-O3 -fomit-frame-pointer'
      - uses: actions/upload-artifact@v3
        with:
          name: web49-mac-release
          path: |
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm