name: Builds
on: [push]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install gcc-11
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.25
          actions-cache-folder: 'emsdk-cache'
      - run: make CC=gcc-11 OPT='-O3 -fomit-frame-pointer -flto' all
      - run: sudo cp bin/miniwasm /usr/bin/miniwasm
      - run: pushd ./; git clone https://github.com/wasm3/wasm3 && cd wasm3 && cmake . && sudo make -Bj install; popd
      - run: sudo apt install -y python3 python3-pip
      - run: pip3 install matplotlib
      - run: python3 bench.py
      - uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path:  |
            test/bench/fannkuch-redux.png
            test/bench/mandelbrot.png
            test/bench/binary-trees.png
            test/bench/nop.png
            test/bench/fib.png
            test/bench/mandelbrot-simd.png
            test/bench/fasta.png
            test/bench/nbody.png
            test/bench/fibf.png
            test/bench/coremark.png
  freebsd-web49:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
      - uses: actions/checkout@v3
      - name: Test in FreeBSD
        id: test
        uses: vmactions/freebsd-vm@v0
        with:
          usesh: true
          prepare: |
            pkg install -y glfw gcc
          run: |
            make CC=gcc OPT='-O3 -fomit-frame-pointer -flto' all bin/raywasm
      - uses: actions/upload-artifact@v3
        with:
          name: web49-freebsd-release
          path:  |
            emraylib
            bin/raywasm
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  linux-web49:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install libgl1-mesa-dev libglfw3-dev
      - run: make CC=cc OPT='-O3 -fomit-frame-pointer' all bin/raywasm
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-release
          path:  |
            emraylib
            bin/raywasm
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  linux-web49-warnings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install libgl1-mesa-dev libglfw3-dev
      - run: make CC=cc OPT='-g3' CFLAGS='-Wall -Wextra -Werror -Wno-unused-parameter' all bin/raywasm
      - uses: actions/upload-artifact@v3
        with:
          name: web49-linux-debug
          path:  |
            emraylib
            bin/raywasm
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm
  macos-web49:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: brew install glfw
      - run: make CC=clang UNAME_S=Darwin OPT='-O3 -fomit-frame-pointer -flto' all bin/raywasm
      - uses: actions/upload-artifact@v3
        with:
          name: web49-mac-release
          path: |
            emraylib
            bin/raywasm
            bin/wasm2wat
            bin/wat2wasm
            bin/wasm2wasm
            bin/miniwasm